version: "3.8"

services:
  new-mysql:  # 수정: 서비스 이름 변경
    image: mysql:8.0
    container_name: new-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trip
    ports:
      - "3306:3306"
    networks:
      - new-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5

  new-spring:  # 수정: service 이름 통일
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-spring
    depends_on:
      new-mysql:  # 수정: 참조 이름 일치
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://new-mysql:3306/trip  # 수정: 서비스 이름 반영
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - new-network

networks:
  new-network:
    driver: bridge
