version: "3.8"

services:
  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    networks:
      - new-network  # 기존 네트워크를 사용
    external: true  # 외부에 이미 존재하는 컨테이너를 사용

  new-spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-spring
    depends_on:
      - mysql-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/trip
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - new-network

networks:
  new-network:
    external: true  # 기존 네트워크 사용
