version: "3.8"

services:
  mysql-container:
    external: true  # 이미 실행 중인 mysql-container를 사용

  new-spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-spring
    depends_on:
      - mysql-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/trip
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - new-network

networks:
  new-network:
    external: true  # 외부 네트워크를 사용
