version: "3.8"

services:
  new-mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trip
    ports:
      - "3306:3306"
    networks:
      - new-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql  # 익명 볼륨

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container  # 컨테이너 이름 중복 방지
    depends_on:
      - new-mysql  # 간단히 서비스 이름 참조
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://new-mysql:3306/trip
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - new-network
    restart: unless-stopped

volumes:
  mysql-data:  # 익명 볼륨 선언

networks:
  new-network:  # 하나의 네트워크 이름으로 통일
    driver: bridge
