version: "3.8"

services:
  new-spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-spring
    depends_on:
      # 종속 관계를 제거합니다. 기존 컨테이너와 연결만 합니다.
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/trip
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - new-network

networks:
  new-network:
    external: true  # 기존 네트워크 사용
