version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: samsungdb
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_VOLUME:-/home/ec2-user/actions-runner/_work/trip/trip/mysql-data}:/var/lib/mysql  # 환경 변수를 처리
    networks:
      - git-actions-auto_my-network
    restart: unless-stopped  # 컨테이너가 중지되거나 재시작되지 않도록 설정

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/samsungdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql
    networks:
      - git-actions-auto_my-network
    restart: unless-stopped  # 컨테이너가 중지되거나 재시작되지 않도록 설정

volumes:
  mysql-data:
    driver: local  # 로컬 볼륨 사용

networks:
  git-actions-auto_my-network:
    driver: bridge  # Docker 네트워크 사용
