version: "3.8"

services:
  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trip
    ports:
      - "3306:3306"
    networks:
      - new-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 5

  new-spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-spring
    depends_on:
      mysql-container:
        condition: service_healthy  # 헬스체크 기반 의존성
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/trip
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - new-network

networks:
  new-network:
    driver: bridge
