name: CI/CD Docker

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/trip
  VERSION: ${{ github.sha }}
  NAME: go_cicd
  DOCKER_COMPOSE_FILE: /home/ec2-user/actions-runner/_work/trip/trip/docker-compose.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: geonmoo2/trip

      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache docker layers
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-go ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: geonmoo2/trip

      - name: Print working directory
        run: pwd

      - name: List files in current directory
        run: ls -al /home/ec2-user/actions-runner/_work/trip/trip/

      - name: Debug docker-compose file path
        run: |
          echo "DOCKER_COMPOSE_FILE: ${{ env.DOCKER_COMPOSE_FILE }}"
          ls -al ${{ env.DOCKER_COMPOSE_FILE }}

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Stop and remove existing containers
        run: |
          sudo docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} down || true

      - name: Docker Compose setup
        run: |
          sudo docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} pull
          sudo docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d --build --remove-orphans
