name: CI/CD Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/trip
  VERSION: ${{ github.sha }}
  NAME: go_cicd
  DOCKER_COMPOSE_FILE: /home/ec2-user/actions-runner/_work/trip/trip/repo/docker-compose.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache docker layers
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-go ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare files
        run: |
          mkdir -p /home/ec2-user/actions-runner/_work/trip/trip/repo/
          cp ./docker-compose.yml /home/ec2-user/actions-runner/_work/trip/trip/repo/docker-compose.yml
          cp ./Dockerfile /home/ec2-user/actions-runner/_work/trip/trip/repo/Dockerfile

      - name: Debug files
        run: |
          ls -l /home/ec2-user/actions-runner/_work/trip/trip/repo/
          cat /home/ec2-user/actions-runner/_work/trip/trip/repo/Dockerfile

      - name: Docker Compose setup
        run: |
          sudo docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} pull
          sudo docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d --build --remove-orphans
