deploy:
  needs: build
  name: Deploy
  runs-on: [ self-hosted, label-go ]
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: geonmoo2/trip
        clean: false

    - name: Ensure MySQL data directory exists
      run: |
        mkdir -p /home/ec2-user/actions-runner/_work/trip/trip/mysql-data
        sudo chown -R ec2-user:ec2-user /home/ec2-user/actions-runner/_work/trip/trip/mysql-data/
        sudo chmod -R u+w /home/ec2-user/actions-runner/_work/trip/trip/mysql-data/

    - name: Stop and remove existing containers
      run: |
        sudo docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} down --volumes=false || true

    - name: Connect existing MySQL container to the network
      run: |
        docker network connect new-network mysql-container || true

    - name: Docker Compose setup
      run: |
        sudo docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} pull
        sudo docker-compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d --build --remove-orphans
